ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

/*SELECT username FROM all_users ORDER BY username;*/
/*DROP USER USUARIO1 CASCADE;*/

--CREACION DE USUARIO DUEÑO DE LA BD
CREATE USER USUARIO1 IDENTIFIED BY "DEL1AL8"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

--OTORGAR PERMISOS USUARIO DUEÑO
GRANT CREATE SESSION TO USUARIO1;
GRANT CREATE SYNONYM TO USUARIO1;
GRANT UNLIMITED TABLESPACE TO USUARIO1;
GRANT CREATE TABLE TO USUARIO1;
GRANT CREATE VIEW TO USUARIO1;
GRANT CREATE PROCEDURE TO USUARIO1;
GRANT CREATE SEQUENCE TO USUARIO1;
GRANT CREATE TRIGGER TO USUARIO1;
GRANT SELECT ANY TABLE TO USUARIO1;